import { useState } from 'react';
import type { Metadata } from 'next';
import { Inter, Noto_Sans_Javanese } from 'next/font/google';
import './globals.css';

import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body className={inter.className}>
        <Navigation />
        <main className='flex md:mx-8 mx-4 min-h-screen'>
          <div className='mx-auto md:max-w-4xl w-full'>{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
